[project]
name = "directional-atacom"
version = "0.1.0"
description = "Safe RL libary "
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "airhockeychallenge",
    "directional-atacom",
    "cvxpylayers>=0.1.6",
    "dm-control>=1.0.8",
    "experiment-launcher==3.3",
    "mushroom-rl==1.10.1",
    "numba>=0.60.0",
    "numpy==1.26.4",
    "pyyaml>=6.0",
    "omnisafe",
    "pybullet>=3.2.6",
    "moviepy==2.2.1",
]

[tool.uv.sources]
directional-atacom = { workspace = true }
airhockeychallenge = { path = "external/air_hockey_challenge", editable = true }
omnisafe = { git = "https://github.com/cube1324/omnisafe.git" }

[tool.uv]
package=true
no-build-isolation-package = ["pybullet"]
