[project]
name = "directional-atacom"
version = "0.1.0"
description = "Safe RL libary "
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "airhockeychallenge",
    "directional-atacom",
    "experiment-launcher==3.3",
    "mushroom-rl==1.10.1",
    "wandb",
    "numpy==1.26.4",
    "pyyaml>=6.0",
    "moviepy==2.2.1",
]

[tool.uv.sources]
directional-atacom = { workspace = true }
airhockeychallenge = { path = "external/air_hockey_challenge", editable = true }

[tool.uv]
package=true
