n_epochs: 200
n_steps: 10000

violation_memory_ratio: 0.1

use_viability: True

n_episodes_test: 15

atacom_lam: 50
atacom_beta: 1.0
atacom_dc: False
accepted_risk: 0.5

cost_budget: 5

init_delta: 1
lr_delta: 0.1
delta_warmup_transitions: 50000
constraint_weight_decay: -1 # disable

constr_aggregation: 'none' # none, array, max
constr_aggregation_value_function: 'max' # none, array, max