use_viability: False

n_epochs: 100
n_steps: 20000

slack_limit: 10
atacom_lam: 100
atacom_beta: 1.5

initial_replay_size: 10000
warmup_transitions: 10000
max_replay_size: 200000

learning_rate_actor: 3.e-4
learning_rate_critic: 3.e-4

init_alpha: 0.4
lr_alpha: 1.e-5
target_entropy: -4
batch_size: 64

use_cuda: False

render: False
n_episodes_test: 50

n_features_critic: '256 256'
n_features_actor: '256 256'
activation: 'selu'

