atacom_lam: 25
atacom_beta: 2
atacom_dc: False

render: False

n_epochs: 100
n_steps: 10000

initial_replay_size: 10000
warmup_transitions: 10000
max_replay_size: 200000

learning_rate_actor: 3.e-4
learning_rate_critic: 3.e-4

lr_alpha: 1.e-5
target_entropy: -2
batch_size: 64

use_cuda: False

n_episodes_test: 25

beta_policy: True

n_features_critic: '256 256'
n_features_actor: '256 256'

