n_epochs: 200
n_steps: 10000
n_episodes_test: 25

initial_replay_size: 10000
warmup_transitions: 10000
max_replay_size: 200000
batch_size: 64

learning_rate_actor: 3.e-4
learning_rate_critic: 3.e-4

init_alpha: 0.4
lr_alpha: 1.e-5
target_entropy: -2

beta_policy: True

n_features_actor: '256 256'
n_features_critic: '256 256'
activation: 'selu'

normalize_state: True

use_cuda: False
render: False
